cc_library(
    name = "grid",
    srcs = ["grid.cpp"],
    hdrs = ["grid.h"],
    deps = [":obstacle"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "obstacle",
    srcs = ["obstacle.cpp"],
    hdrs = ["obstacle.h"],
    visibility = ["//visibility:public"],
)
