cc_library(
    name = "radar",
    srcs = ["radar.cpp"],
    hdrs = ["radar.h"],
    deps = ["//src/sensors:sensor"],  # Depends on the base sensor class
    visibility = ["//visibility:public"],  # Make it public so it can be used in main.cpp
)
