cc_test(
    name = "lidar_test",
    srcs = ["lidar/lidar_test.cpp"],
    deps = [
        "//src/sensors/lidar:lidar",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "radar_test",
    srcs = ["radar/radar_test.cpp"],
    deps = [
        "//src/sensors/radar:radar",
        "@googletest//:gtest_main",
    ],
)
