cc_library(
    name = "routing",
    srcs = ["routing.cpp"],
    hdrs = ["routing.h"],
    deps = [
        "//src/vehicle:vehicle",
        "//src/environment:grid",
    ],
    includes = ["src/vehicle"],
    visibility = ["//visibility:public"],
)
